name: swift_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # state
  provider: 4.0.3

  # Base Component
  webview_flutter: ^0.3.19
  flutter_webview_plugin: ^0.3.10
  quiver: ^2.0.5

  # Data
  dio: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.3+5
  locolstorage: ^2.0.0

  # # Html Encoder/Decoder
  # html_unescape: ^1.0.1+3
  # # 解析html标签
  # flutter_html: ^0.10.4
  # # UI
  oktoast: ^2.3.1
  pull_to_refresh: ^1.5.6
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0-rc.1
  # # 谁用谁闪亮
  shimmer: ^1.0.0
  #   # third_app
  url_launcher: ^5.1.6 #启动第三方app
  share: 0.6.2+1 #分享
  # launch_review: ^2.0.0
  # open_file: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: asset/font/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: asset/font/ZCOOLKuaiLe-Regular.ttf
  assets:
    - asset/image/
    # - asset/animation/
    - README.md
flutter_intl:
  enabled: true
